# Generated by Django 4.2.3 on 2023-08-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_comment_options_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
